name: pyjs-relocatable

on:
  workflow_dispatch:
    inputs:
      py_version:
        type: choice
        description: select a python version
        default: '3.9'
        required: true
        options: 
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'      
      pip_modules:
        type: string
        description: provide packages to install (optional)
        required: false

env:
  arch: darwin-x86
  DEV_ID: ${{ secrets.DEV_ID }}

jobs:
  build:
    runs-on: macos-10.15

    steps:

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Setup python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ github.event.inputs.py_version }}

    - name: Display python version
      run: python3 --version

    - name: Import development certificate
      uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.MACOS_DEV_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_DEV_PWD }}

    - name: Build externals with extra modules
      working-directory: ./source/py
      if: github.event.inputs.pip_modules != ''
      run: python3 -m builder pyjs relocatable_pkg --pip-modules="${{ github.event.inputs.pip_modules }}" --install --build

    - name: Build externals
      working-directory: ./source/py
      if: github.event.inputs.pip_modules == ''
      run: python3 -m builder pyjs relocatable_pkg --install --build

    - name: Sign externals and any frameworks in support folder
      run: make sign

    - name: Create package, convert it to a .dmg
      run: make dmg

    - name: Sign .dmg        
      run: make sign-dmg

    # - name: Sign .dmg
    #   run: |
    #     codesign --sign "Developer ID Application: ${{ secrets.DEV_ID }}" \
    #       --deep --force --verbose --options runtime "${{ env.PRODUCT_DMG }}"

    - name: Notarize dmg
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: "${{ env.PRODUCT_DMG }}"
        appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
        appstore-connect-password: ${{ secrets.NOTARIZATION_PWD }}

    - name: Staple externals
      uses: devbotsxyz/xcode-staple@v1
      with:
        product-path: "${{ env.PRODUCT_DMG }}"

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-relocatable-pkg-${{ env.arch }}-${{ github.event.inputs.py_version }}-${{ steps.short-sha.outputs.sha }}
        path: "${{ env.PRODUCT_DMG }}"
