name: test-macos-x86-python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        variant:
          - default
          - shared-pkg
          - shared-ext
          - static-ext
          - framework-pkg
          - framework-ext
          - relocatable-pkg
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: '0'

      - name: cache downloads
        id: cache-downloads
        uses: actions/cache@v3
        env:
          cache-name: pyjs-cache-1
        with:
          path: |
            source/py/targets/build/downloads
            source/py/targets/build/lib/bzip2
            source/py/targets/build/lib/openssl
            source/py/targets/build/lib/xz
          key: $${{ env.cache-name }}-${{ hashFiles('source/py/resources/pyjs-dependencies.txt') }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies

      - name: install python requirements
        run: pip install -r requirements.txt

      - name: Display python version
        run: python3 --version

      - name: build ${{ matrix.variant }}
        run: make ${{ matrix.variant }}

