name: test-macos-x86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: cache downloads
      id: cache-downloads
      uses: actions/cache@v3
      env:
        cache-name: pyjs-cache-1
      with:
        path: |
          source/py/targets/build/downloads
          source/py/targets/build/lib/bzip2
          source/py/targets/build/lib/openssl
          source/py/targets/build/lib/xz
        key: $${{ env.cache-name }}-${{ hashFiles('source/py/resources/pyjs-dependencies.txt') }}

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies

    - name: install python requirements
      run: pip install -r requirements.txt

    - name: Display python version
      run: python3 --version
    
    - name: build_default
      run: make

    - name: build_homebrew_ext
      run: make homebrew-ext

    - name: build_homebrew_pkg
      run: make homebrew-pkg

    - name: build_shared_pkg
      run: make shared-pkg

    - name: build_shared_ext
      run: make shared-ext

    - name: build_static_ext
      run: make static-ext

    - name: build_framework_pkg
      run: make framework-pkg

    - name: build_framework_ext
      run: make framework-ext

    - name: build_relocatable_pkg
      run:  make relocatable-pkg
